name: print-hello
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list files
        run: ls -al
        shell: bash
  
  run-later:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: pull repository
      - name: list files
        run: echo "Run at last"
        shell: bash

