name: print-hello
run-name: ${{ github.actor }} is running on sh
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list files
        run: echo "Hi""
        shell: bash

