name: print-hello
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list files
        run: ls -al
        shell: bash

  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo 'Hello Developers!'
        shell: bash

