name: print-hello
on:
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list files
        run: mn
        shell: bash

