name: Hello world workflow

on:
  push:
	branches:
	  - main
  pull_request:
	branches:
	  - main
  workflow_dispatch:

jobs:
  hello:
	runs-on: ubuntu-latest
	steps:
	  - name: print-hello
		run: echo "Hello Developers!"
		shell: bash
