name: second yaml
run-name: ${{ github.actor }} is running on bash

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  check-seond:
    runs-on: ubuntu-lastest
    steps:
      - run: ls
      - uses: actions/checkout@v4
      - name: checkout
        run: ls -al
